# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12
  - PG_SUPPORTED_VERSIONS=13
  - PG_SUPPORTED_VERSIONS=14
  - PG_SUPPORTED_VERSIONS=15

language: C
dist: bionic

before_install:
  # extra apt.pg.o.sh options added in version 204, travis currently has 199 (2019-11-27)
  - sudo apt-get -qq update
  - sudo apt-get -y install postgresql-common libhealpix-cxx-dev docbook-dsssl docbook-xml openjade

install:
  - sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -v $PG_SUPPORTED_VERSIONS -i

script:
  - make PROFILE="-Werror"
  - sudo make install
  - pg_virtualenv make installcheck
  - if test -s regression.diffs; then cat regression.diffs; exit 1; fi
  - pg_virtualenv make test
  - if test -s regression.diffs; then cat regression.diffs; exit 1; fi
  - pg_virtualenv make crushtest
  - if test -s regression.diffs; then cat regression.diffs; exit 1; fi
  - make -C doc
  - sudo make -C doc install
